// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANx_de4Ckxse9_CQAPvda0vUfi4ssA1cI',
    appId: '1:356757392729:web:a24ebe4a5432eed5511048',
    messagingSenderId: '356757392729',
    projectId: 'connect-2fba0',
    authDomain: 'connect-2fba0.firebaseapp.com',
    storageBucket: 'connect-2fba0.firebasestorage.app',
    measurementId: 'G-C1PVFVF9LR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYqC2-VtiMZCC7ZaCCzaGqo6ocv8lHzY4',
    appId: '1:356757392729:android:3ab6f5a78d204235511048',
    messagingSenderId: '356757392729',
    projectId: 'connect-2fba0',
    storageBucket: 'connect-2fba0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADCmTO2l8auBAHVfk_KAUV_fgK40shT5Y',
    appId: '1:356757392729:ios:166e6f72d602b342511048',
    messagingSenderId: '356757392729',
    projectId: 'connect-2fba0',
    storageBucket: 'connect-2fba0.firebasestorage.app',
    iosBundleId: 'com.example.connectFb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADCmTO2l8auBAHVfk_KAUV_fgK40shT5Y',
    appId: '1:356757392729:ios:166e6f72d602b342511048',
    messagingSenderId: '356757392729',
    projectId: 'connect-2fba0',
    storageBucket: 'connect-2fba0.firebasestorage.app',
    iosBundleId: 'com.example.connectFb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANx_de4Ckxse9_CQAPvda0vUfi4ssA1cI',
    appId: '1:356757392729:web:f9d4782472560602511048',
    messagingSenderId: '356757392729',
    projectId: 'connect-2fba0',
    authDomain: 'connect-2fba0.firebaseapp.com',
    storageBucket: 'connect-2fba0.firebasestorage.app',
    measurementId: 'G-B4D9SH2VJ8',
  );
}
